#!/bin/bash

echo "Running Test..."

flutter drive \
  --driver=test_driver/integration_test_driver.dart \
  --target=integration_test/about_us_page_test.dart

flutter drive \
  --driver=test_driver/integration_test_driver.dart \
  --target=integration_test/add_label_page_test.dart

flutter drive \
  --driver=test_driver/integration_test_driver.dart \
  --target=integration_test/add_project_page_test.dart

flutter drive \
  --driver=test_driver/integration_test_driver.dart \
  --target=integration_test/add_task_page_test.dart

flutter drive \
  --driver=test_driver/integration_test_driver.dart \
  --target=integration_test/completed_tasks_page_test.dart

flutter drive \
  --driver=test_driver/integration_test_driver.dart \
  --target=integration_test/home_page_test.dart

echo "Running Test Completed!!"