# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    match(app_identifier: "burhanrashid52.whattodo", type: "appstore",readonly:true)
    updated_version_number = bump_build_number()
    increment_build_number(build_number: updated_version_number)
    increment_version_number(version_number: ENV["FLUTTER_BUILD_NAME"])
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    pilot(api_key_path: "fastlane/store.json", skip_waiting_for_build_processing: true)
  end

  def bump_build_number()
    latest_build_number = latest_testflight_build_number(initial_build_number: 0,api_key_path: "fastlane/store.json")
    return (latest_build_number + 1)
  end
end
