# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :beta do
    updated_version_name = ENV["FLUTTER_BUILD_NAME"]
    updated_version_number = ENV["FLUTTER_BUILD_NUMBER"]
    sh "flutter build apk --release --build-name=#{updated_version_name} --build-number=#{updated_version_number}"
    upload_to_play_store(
      track: "internal",
      apk: "../build/app/outputs/flutter-apk/app-release.apk",
    )
  end
end
